### PR TITLE
readding tl;dr page to protocol path

### LINKED ISSUE #57: Broken links
**Describe the bug**
Some links returns 404

**To Reproduce**
1. Go to 'optimism.io'
2. Click on 'Tutorial'
3. See error 404 and 'Not secure' warning

Same with http://community.optimism.io/docs/protocol/tldr.html

### PR DESCRIPTION
**Pull request by platocrat**
**Metadata**
- Fixes #57

### CODE REVIEW

**Comment by smartcontracts** [comment]
How does this fix the issue?

**Comment by platocrat** [comment]
> How does this fix the issue?

@smartcontracts The mistake I made in this PR was that it started out as an attempt to merge to `ethereum-optimism:experimental` which was the previous `HEAD`, so I had an issue in being able to create a single commit.

I changed the base branch to `main` which fixed most things.
One minor weird thing now is that the content that was added in #62 is shown as being new content.

**Comment by smartcontracts** [comment]
Hmmmm could we try doing this PR against a fresh pull of the `main` branch?

**Comment by platocrat** [comment]
PR #64 is the replacement for this PR.

**Pull request closed without merging**
