### PR TITLE
Add Waffle docs

### PR DESCRIPTION
**Pull request by yivlad**
**Description**
Mention [Waffle](https://github.com/TrueFiEng/Waffle) testing framework in `Using your favorite tools` section.

### CODE REVIEW

**Comment by Nicca42** [comment]
@qbzzt can you use these instructions and confirm they work?

**Comment by qbzzt** [comment]
The first step failed. 

I ran: 
```
npm install --save-dev ethereum-waffle@alpha @ethereum-waffle/optimism@alpha |& tee x
```

And got 
[tee-output.txt](https://github.com/ethereum-optimism/community-hub/files/8825123/tee-output.txt)

The log file is 
[npm.log](https://github.com/ethereum-optimism/community-hub/files/8825133/npm.log)

There's probably a simple solution, but it needs to be in the doc for people who don't know waffle well, such as me. 

@yivlad , can you add this please?

**Comment by yivlad** [comment]
@qbzzt pushed a note to install `make`, thanks for bringing this up! Also do you want a fully reproducible example in the docs? I think there might be too much boilerplate code

**Comment by yivlad** [comment]
Hey @qbzzt, totally makes sense! Created a [PR](https://github.com/ethereum-optimism/optimism-tutorial/pull/109) with the tutorial. Can you take a look please?

**Review by qbzzt — APPROVED** [review]
Thank you. With a working tutorial, I think this is all that is required.

**Comment by yivlad** [comment]
@Nicca42 can I get approve for this please?

**Pull request merged**
