### PR TITLE
feat: update to new style

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
This PR updates the community hub style significantly. Although it's not 100% identical to the figma designed by @lanceplaine, it's probably as close as we'll get without doing a full rework of the frontend. I'm pretty happy with it. I disabled dark mode for now, we can get that working later.

### CODE REVIEW

**Comment by Nicca42** [comment]
Looks good to me, but lets wait for @lanceplaine

**Comment by lanceplaine** [comment]
- [ ] Multiple tabs are being marked as active when browsing `http://localhost:8080/`. I would hide `Guide` and `Contribute` until we have dedicated pages for them.
Tabs

**Comment by lanceplaine** [comment]
- [ ] Remove `box-shadow` on the `<aside class="sidebar">` element.
- [ ] There is a white bg on the logo. It shouldn't be visible because the topbar should be white. Looks like the UI bugs also comes from the the `box-shadow` on the `<aside class="sidebar">` element.

Box Shadow

White BG on logo

**Comment by lanceplaine** [comment]
- [ ] For "Dev docs", "Tools for Devs" and "Protocol" sections we should add content for the overview page. Currently it's empty.
Empty Overview Page

**Comment by smartcontracts** [comment]
> * [ ]  For "Dev docs", "Tools for Devs" and "Protocol" sections we should add content for the overview page. Currently it's empty.

This will be added in other PRs.

**Comment by lanceplaine** [comment]
- [ ] Is it possible to make the first level of left side tabs semibold? See code vs. mocks below:
Left Nav - Code
Left Nav - Mocks

**Comment by lanceplaine** [comment]
- [ ] It would be good to have the left tabs taking the full width so they are easier to click. See code vs mock below:
Full width tab - Code
Full width tab - Mock

**Comment by lanceplaine** [comment]
- [ ] It might not be for this PR but tabs should use "Sentence case"

**Comment by lanceplaine** [comment]
- [ ] Is there a way to make the right sidebar automatically update based on scrolling?

Scroll
Follow Scroll

**Comment by lanceplaine** [comment]
Otherwise Looks good to me 👏

**Comment by smartcontracts** [comment]
> 

Hmmm... I thought this was working earlier but I guess not.

**Review by lanceplaine — APPROVED** [review]

**Pull request merged**
