### PR TITLE
Add Blast to Optimism documentation

### PR DESCRIPTION
**Pull request by stefancristianco**
**Description**
We have added Optimism Mainnet dedicated API support and Public API support on :
https://blastapi.io/
https://blastapi.io/public-api

We also wanted these features to be reflected in the documentation, so developers can use them right away.

**Additional context**

**Metadata**

### CODE REVIEW

**Comment by Nicca42** [comment]
@qbzzt can you verify this works?

**Comment by qbzzt** [comment]
> @qbzzt can you verify this works?

Verified, it works.

**Comment by stefancristianco** [comment]
> It doesn't seem to be working correctly. I can't even deploy a contract with it.

Hi @qbzzt,

Your finding is correct. We implemented some extra security layers (we've added a WAF layer through CloudFlare which also supposed DNS migrations and extra configurations) which caused requests coming from Asia to be rate-limited. The traffic was seen as coming from the same source IP (namely the IP of a CloudFlare service, since the traffic was proxied through CloudFlare) which caused the IP rate-limiting to interfere with the service. Since then, we've handled this issue and our RPC endpoints are no longer affected.
Could you please check this PR again.

Thanks a lot!

**Comment by qbzzt** [comment]
We are removing the list of providers from networks.md (it's too long and dynamic) and replacing it with a link - so it does not make sense to add you to that list.

**Pull request closed without merging**
