### PR TITLE
Rewrote paragraph in proper format.

### PR DESCRIPTION
**Pull request by besoeasy**

### CODE REVIEW

**Review by smartcontracts — APPROVED** [review]
LOL sorry -- approved

**Comment by smartcontracts** [comment]
Send me an ETH address and I'll make you an NFT for this PR lolol

**Comment by besoeasy** [comment]
@smartcontracts 

 mrfas.eth or 0x823c37c82ff936459a0a7d3e3488989456ba5d46

**Comment by smartcontracts** [comment]
Senttt https://opensea.io/assets/0x495f947276749ce646f68ac8c248420045cb7b5e/34765029840658706893803010833957019895695699803719888420488474710352213311489

**Pull request merged**
