### PR TITLE
adding the new tool moodyeth

### PR DESCRIPTION
**Pull request by jjhesk**
**Description**
Adding new python tool as the dev tool

**Metadata**
- add tool

### CODE REVIEW

**Comment by Nicca42** [comment]
@qbzzt have you checked this?

**Comment by qbzzt** [comment]
No, I will try to do it tomorrow

**Comment by qbzzt** [comment]
To do a proper job I'll need to learn it to the getting started level, so I'll add it there too.

**Comment by qbzzt** [comment]
Moodyeth is not sufficiently well documented to be usable.

**Pull request closed without merging**
