### PR TITLE
Update providers.md with Pocket Network

### PR DESCRIPTION
**Pull request by larrybird0x**
**Description**
Added Pocket Network to the list of Node Providers for Optimism

**Additional context**
Pocket Network is a decentralized, multi-chain RPC protocol.

### CODE REVIEW

**Comment by qbzzt** [comment]
> @qbzzt can you verify this?

Verified - it works.

**Comment by qbzzt** [comment]
> May I ask why?

Because we don't want to show favorites. I think the fairest thing would be to organize the providers by alphabetical order. @Nicca42 , do you agree?

**Comment by larrybird0x** [comment]
> 



> > May I ask why?
> 
> Because we don't want to show favorites. I think the fairest thing would be to organize the providers by alphabetical order. @Nicca42 , do you agree?

It wasn't / isn't in Alphabetical order before I submitted the PR

**Comment by qbzzt** [comment]
I know, we still haven't officially decided to do that - that message was
me discussing it.

**Comment by larrybird0x** [comment]
> @qbzzt can you verify this?
> 
> Also @larrybird0x please add this to the bottom of the list, not the top. Thanks!

In the meantime, I moved Pocket Network to the bottom @Nicca42.

I like @qbzzt's idea of re-organizing the list into alphabetical order, out of fairness.

**Review by Nicca42 — APPROVED** [review]

**Pull request merged**
