### PR TITLE
Fix typo in CrossDomainMessenger documentation

### LINKED ISSUE #289: Typo in CrossDomainMessenger documentation
image
 There is a docs issue. Should modify 
```
abi.encodeWithSignature(
      "doSomething(uint256)",
      myFunctionParam
),

```
to
```
abi.encodeWithSignature(
      "doSomething()",
      myFunctionParam
),
```

### PR DESCRIPTION
**Pull request by LeifuChen**
**Description**
Fix the typo in developer doc

**Metadata**
- Fixes #289

### CODE REVIEW

**Review by Nicca42 — CHANGES_REQUESTED** [review]
Could you add the unit256 to both rather than removing it? Without an example parameter it can be confusing. Thanks!

**Comment by smartcontracts** [comment]
Ah @LeifuChen I think what @Nicca42 is asking is that instead of removing uint256 from the line in question, to instead add a uint256 parameter to the following two lines:
1. https://github.com/ethereum-optimism/community-hub/blob/009c3c4cded147bc8ee77a25ed8382d5e51f51c1/src/docs/developers/bridge/messaging.md?plain=1#L42
2. https://github.com/ethereum-optimism/community-hub/blob/009c3c4cded147bc8ee77a25ed8382d5e51f51c1/src/docs/developers/bridge/messaging.md?plain=1#L100

**Comment by LeifuChen** [comment]
@smartcontracts Thanks for your clarification. 
@Nicca42 The change has been made. Please check the results. Thanks.

**Comment by Nicca42** [comment]
Looks great! Thank you @LeifuChen 🙏

**Review by Nicca42 — APPROVED** [review]
🙏 Looks great.

**Pull request merged**
