### PR TITLE
page: Add a "dev dump" page for things that will eventually have their own page

### PR DESCRIPTION
**Pull request by smartcontracts**
Will keep updating this as I see useful things to put inside it.

### CODE REVIEW

**Comment by platocrat** [comment]
Any updates on the dev dump pages?

**Comment by smartcontracts** [comment]
Eh we could probably just add this page as-is. Can always make PRs in the future to add new stuff. Wdyt @platocrat?

**Comment by platocrat** [comment]
Adding it now and adding/editing content as we go sounds like a solid plan.

**Comment by smartcontracts** [comment]
kk! let's try to just get this merged then

**Review by platocrat — APPROVED** [review]

**Pull request merged**
