### PR TITLE
feat: Community Hub refresh

### PR DESCRIPTION
**Pull request by smartcontracts**
Community Hub is getting a big refresh! Community Hub is being moved over to Nextra in line with the Optimism Docs repo. This means the two repositories can share a common development flow.

### CODE REVIEW

**Comment by smartcontracts** [comment]
Working on getting the last two links fixed.

**Comment by smartcontracts** [comment]
Note that Netlify CI checks will fail because this is a completely different build process. We will have to edit the build process in CI once it's merged.

**Comment by sbvegan** [comment]
damn this is a thicc one but also a much needed one, thanks for putting it up!

**Review by sbvegan — COMMENTED** [review]
The landing page side menu looks off. What do you think about moving the top bar links to the left hand navbar? And then leaving the top bar sparse, maybe with just a link to the technical docs and governance forum?

Screenshot 2024-08-14 at 11 11 12 AM

**Comment by opmxwell** [comment]
@sbvegan this is a great callout thank you 🙏 - imo I think we can keep it as is with the top bar for now and, and always revisit down the line if needed. The sidebar is also just sparse on the homepage, but its get populated more if you click on any of the sections.

**Review by opmxwell — APPROVED** [review]

**Review by opmxwell — APPROVED** [review]

**Pull request merged**
