### PR TITLE
Update explorers.md

### PR DESCRIPTION
**Pull request by sneg55**
**Description**

Added dexguru blockexplorer to the list of OP block explorers. 

**Tests**

n/a
**Additional context**

n/a
**Metadata**

n/a

### CODE REVIEW

**Comment by qbzzt** [comment]
I approve

**Review by qbzzt — APPROVED** [review]

**Comment by sneg55** [comment]
@OPMattie @Nicca42 can you please review this PR? Thanks

**Comment by sneg55** [comment]
Hi @qbzzt @mslipper @zchn @hboon can you please review it? It's been sitting here for a while. 

Thanks!

**Comment by sbvegan** [comment]
Hello, thank you taking the time to write this and I apologize for the delayed response. We're putting a pause on these types of documentation updates until we have a formal process in place. In the meantime please consider filling out this [form](https://airtable.com/appQ2S9IatldkoNQw/shr2e75GnXRqi6yTM). We update our [ecosystem page](https://www.optimism.io/apps/all) weekly and it would be great to have you included.

**Pull request closed without merging**
